// SPDX-License-Identifier: BSD-3-Clause
#include <argp.h>//boris:use for parsing.
#include <unistd.h>
#include "bpfKillExecve.skel.h"//boris: autogenerated by makefile, a particular BTF(bpf-type-format)-related header file.
#include "common_um.h"
#include "common.h"

//boris: for envirionment- and argument-setting.
static struct env {
    int target_ppid; //boris: ppid means parent procces ID.
} env;

const char *argp_program_version = "bpfKillExecve 1.0";
const char *argp_program_bug_address = "<boris.dev>";
const char argp_program_doc[] =

"USAGE:sudo ./bpfKillExecve \n";


static const struct argp_option opts[] = {
    {},
    {},
};


static error_t parse_arg(int key, char *arg, struct argp_state *state)//boris: handle parsing : command-line-intput
{
    switch (key) {
    case ARGP_KEY_ARG:
        argp_usage(state);
        break;
    default:
        return ARGP_ERR_UNKNOWN;
    }
    return 0;
}
static const struct argp argp = {
    .options = opts,
    .parser = parse_arg,
    .doc = argp_program_doc,
};

static int handle_event(void *ctx, void *data, size_t data_sz)
{
    const struct event *e = data;
    if (e->success)
        printf("Successfully killed PID %d (%s) for trying to use execve syscall\n", e->pid, e->comm);
    else
        printf("Failed to kill PID %d (%s) for trying to use execve syscall\n", e->pid, e->comm);
    return 0;
}

int main(int argc, char **argv)
{
    struct ring_buffer *rb = NULL;//boris: user-side, to set up ring-buffer
    struct bpfKillExecve_bpf *skel;//boris: bpfKillExecve's skeleton
    int err;//boris: error-handling, auf-jeden-fall!

    // boris: do parsing.(from command-line)
    err = argp_parse(&argp, argc, argv, 0, NULL, NULL);
    if (err) {
        return err;
    }

    // boris: do common setup.
    if (!setup()) {
        exit(1);
    }

    // boris: try to open our bpf program.
    skel = bpfKillExecve_bpf__open();
    if (!skel) {
        fprintf(stderr, "Failed to open BPF program: %s\n", strerror(errno));
        return 1;
    }

    // boris: set target ppid
    skel->rodata->target_ppid = env.target_ppid;

    // boris: try to verify and load our bpf program to kernel.
    err = bpfKillExecve_bpf__load(skel);
	if (err) {
		fprintf(stderr, "Failed to load and verify BPF skeleton\n");
		goto cleanup;
	}

    // boris: try to attach our bpf program to kernel.
    err = bpfKillExecve_bpf__attach( skel);
    if (err) {
        fprintf(stderr, "Failed to attach BPF program: %s\n", strerror(errno));
        goto cleanup;
    }

    
    //boris:we, in user-side, have to set up ring-buffer, so that bpf_KillExecve (in the kernel) can 
    //eventually send info back to user-side. 
    rb = ring_buffer__new(bpf_map__fd( skel->maps.rb), handle_event, NULL, NULL);
    if (!rb) {
        err = -1;
        fprintf(stderr, "Failed to create ring buffer\n");
        goto cleanup;
    }

    printf("Successfully started!\n");
    printf("Sending SIGKILL signal to any program using the bpf syscall execve\n");
    while (!exiting) {
        err = ring_buffer__poll(rb, 100 /* timeout, ms */);
        /* Ctrl-C will cause -EINTR */
        if (err == -EINTR) {
            err = 0;
            break;
        }
        if (err < 0) {
            printf("Error polling perf buffer: %d\n", err);
            break;
        }
    }

cleanup:
    bpfKillExecve_bpf__destroy(skel);//boris:destroy bpf skeleton.
    return -err;
}
